### ISSUE TITLE
Tail Recursion Questions

### ISSUE THREAD

**Issue by Ejdems666** [cphbus-functional-programming/spring-2018#1]
Hi, I'm having some troubles understanding the example provided with the virtual machine manual
[here](https://cphbus-functional-programming.github.io/spring-2018/virtual-cpu.html)

For instance what does the PUSH do?

PUSH r | [–SP] ← r; IP++

What I think I understand is that It adds one to instruction pointer. And it also puts the value of registry passed in argument into a negative stack pointer? What does that mean?

**Comment by Ejdems666** [comment]
@Jegp

**Comment by Jegp** [comment]
Thanks for reaching out Adam! :-)
The first entry before the `|` is the name of the instruction.
The `[-SP]` is supposed to have been `[--SP]`, i. e. a decrement of the stack pointer **before** use. So if the stack pointer was 2 before, it will now become one. And that means that the value `r` is stored at the stack address 1.
Finally, the instruction pointer is incremented by one.

**Comment by Jegp** [comment]
Looks like an HTML formatting issue. The decrement should be correctly rendered here: https://github.com/cphbus-functional-programming/spring-2018/blob/master/docs/virtual-cpu.md.

**Comment by Ejdems666** [comment]
The instruction pointer is incremented in the end you mean, right?

**Comment by Jegp** [comment]
Exactly. My apologies. I updated my reply.
