### ISSUE TITLE
Haskell full stack CORS problem

### ISSUE THREAD

**Issue by Ejdems666** [cphbus-functional-programming/spring-2018#3]
Hi I'm getting this error when I try to send POST request from my Elm frontend to the Haskell backend

`
HTTP header requested in Access-Control-Request-Headers of CORS request is not supported; requested: content-type; supported are Accept, Accept-Language, Content-Language.`

I only have this one line in the scotty do function:

```
scotty 3003 $ do
    middleware simpleCors
...
```

I guess I need some special CORS method, do you happen to know which one? @Jegp

**Comment by Jegp** [comment]
Hi Adam,
Hmmm that's weird. @eguahlak have you seen this before?
Cheers,

**Comment by eguahlak** [comment]
Has to see the whole project!

GitHub repo?

Anders K:-)

**Comment by Ejdems666** [comment]
https://github.com/Ejdems666/haskell-elm-full-stack @eguahlak
